# version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped



  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A biget.celery worker -l info -P gevent -c 4
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=biget.settings
    depends_on:
      - redis
      - websocket

    restart: unless-stopped

  # celery_beat:
  #   build: .
  #   command: celery -A biget beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - .env
  #   environment:
  #     - DJANGO_SETTINGS_MODULE=biget.settings
  #   depends_on:
  #     - redis
  #     - websocket
  #   restart: unless-stopped

  websocket:
    build: .
    command: python manage.py start_websocket
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped

volumes:
  redis_data:
  staticfiles: