# Generated by Django 4.2.23 on 2025-07-01 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ballist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='订单ID')),
                ('acc_fill_sz', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='已成交数量')),
                ('avg_px', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='平均价格')),
                ('c_time', models.DateTimeField(blank=True, null=True, verbose_name='创建时间')),
                ('fee', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='手续费')),
                ('fill_px', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='成交价格')),
                ('fill_sz', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='成交数量')),
                ('fill_time', models.DateTimeField(blank=True, null=True, verbose_name='成交时间')),
                ('inst_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易对ID')),
                ('inst_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='交易类型')),
                ('ord_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='订单类型')),
                ('pnl', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='盈亏')),
                ('pos_side', models.CharField(blank=True, max_length=10, null=True, verbose_name='持仓方向')),
                ('side', models.CharField(blank=True, max_length=10, null=True, verbose_name='订单方向')),
                ('lever', models.CharField(blank=True, max_length=10, null=True, verbose_name='杠杆倍数')),
                ('slOrdPx', models.CharField(blank=True, max_length=50, null=True, verbose_name='止损委托价')),
                ('slTriggerPx', models.CharField(blank=True, max_length=50, null=True, verbose_name='止损触发价')),
                ('state', models.CharField(blank=True, max_length=20, null=True, verbose_name='订单状态')),
                ('sz', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='订单总数量')),
                ('trade_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='交易ID')),
                ('u_time', models.DateTimeField(blank=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户当前订单信息',
                'verbose_name_plural': '用户当前订单信息',
            },
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_datetime', models.DateTimeField(blank=True, null=True, verbose_name='更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='伪删除标记')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('apikey', models.CharField(max_length=100, verbose_name='用户apikey')),
                ('secret', models.CharField(max_length=100, verbose_name='用户secret')),
                ('user_type', models.CharField(choices=[('real', '真实用户'), ('simulated', '模拟用户')], max_length=100, verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '用户配置列表',
                'verbose_name_plural': '用户配置列表',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_datetime', models.DateTimeField(blank=True, null=True, verbose_name='更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='伪删除标记')),
                ('order_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='订单ID')),
                ('position_type', models.CharField(blank=True, choices=[('regular', '普通订单'), ('isolated', '逐仓合约'), ('cross', '全仓合约')], max_length=100, null=True, verbose_name='持仓类型')),
                ('currency', models.CharField(blank=True, max_length=100, null=True, verbose_name='币种名称')),
                ('leverage', models.CharField(blank=True, max_length=100, null=True, verbose_name='持仓倍数')),
                ('direction', models.CharField(blank=True, choices=[('long', '做多'), ('short', '做空')], max_length=100, null=True, verbose_name='持仓方向')),
                ('margin', models.CharField(blank=True, max_length=100, null=True, verbose_name='保证金')),
                ('position_amount', models.CharField(blank=True, max_length=100, null=True, verbose_name='持仓金额')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xysz.userconfig', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户持仓信息',
                'verbose_name_plural': '用户持仓信息',
            },
        ),
        migrations.CreateModel(
            name='Userbal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_datetime', models.DateTimeField(blank=True, null=True, verbose_name='更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='伪删除标记')),
                ('currency', models.CharField(max_length=100, verbose_name='币种')),
                ('avail_bal', models.DecimalField(decimal_places=16, max_digits=50, verbose_name='可用余额')),
                ('eq_usd', models.DecimalField(decimal_places=16, max_digits=50, verbose_name='总权益（美元）')),
                ('frozen_bal', models.DecimalField(decimal_places=16, max_digits=50, verbose_name='冻结余额')),
                ('upl', models.DecimalField(decimal_places=16, max_digits=50, verbose_name='未实现盈亏')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xysz.userconfig', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户账户余额列表',
                'verbose_name_plural': '用户账户余额列表',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_datetime', models.DateTimeField(blank=True, null=True, verbose_name='更新日期')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='伪删除标记')),
                ('currency', models.CharField(max_length=100, verbose_name='币种')),
                ('balance', models.DecimalField(decimal_places=16, max_digits=50, verbose_name='持仓量')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xysz.userconfig', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户账户列表',
                'verbose_name_plural': '用户账户列表',
            },
        ),
    ]
